language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: gAQvFCQxRjDT/xCivdxLEADu3DcXoX8QGEYdRktKsSRyEcUW+T6J1kEHtNSdFxhxENazXXyAVk+sadwAvy3NRI5PDYsDLfW0giLnsrTLWYO+f9z8jCVgMfj3RPk8bxyJW8j1sbnGmGo0EzjddBkyIx3KQl3utj7WpkchltNKdTo=
  - secure: GeYKR/MMExrgu/b8+FUUvY/mfdimIuzXqwzhLqCYWgkje8Dc0hgTpDu9OJUWznGzHB6oE8nBmnpKHvdfvXYjoEWmqjd4y887S0nnckkKTYIpM7edNmzKt4ysPmp7/wZWJ6qdrwKSmKGSHKn/YMzLGY+tXpntQQANvdBnBuykEE8=
